### ISSUE TITLE
Custom Component-Entity System

### ISSUE THREAD

**Issue by excaliburHisSheath** [excaliburHisSheath/Gunship#93]
EntityX is a pretty solid framework, but Gunship requires certain functionality that it doesn't offer. It would be possible to modify my fork of entityx to do what I want, but at that point I may as well write my own for the sake of getting that experience.

**Comment by excaliburHisSheath** [comment]
At this point the required functionality of the ECS is done (we're pretty much up to parity with the previous EntityX implementation), but there are performance issues to be hashed out. Since the fixes are likely to be breaking I'm going to hold off on merging the changes in until I've got the most breaking changes made.

**Comment by randomPoison** [comment]
This has been completed with the lastest PR.
