### ISSUE TITLE
Pool Ogre SceneNodes

### ISSUE THREAD

**Issue by excaliburHisSheath** [excaliburHisSheath/Gunship#95]
I asked about unused scene nodes [on the ogre forums](http://ogre3d.org/forums/viewtopic.php?f=5&t=82524), and while the answer wasn't conclusive it seems like it would at least be a good idea to pool and reuse scene nodes. Even if the performance impact isn't that big it should still be cheaper to reuse existing ones rather than creating and destroying them constantly.

**Comment by randomPoison** [comment]
This was completed as part of the custom ECS framework.
